music_directory "/music"
bind_to_address "0.0.0.0"
port "6600"

audio_output {
    type "alsa"
    name "Stereo"
    device "alsa_output.platform-rk809-sound.stereo-fallback"
    mixer_type "software"
}
